### ISSUE TITLE
Stops working within a couple of hours

### ISSUE THREAD

**Issue by dkduck** [gruijter/com.gruijter.virtualradar#3]
Hi

I have installed Virtualradar and it works like a charm, until it have been running for som hours, then it stops working with the below error:

2018-07-10 11:31:49 [log] [ManagerDrivers] [radar] [0] { Error: socket hang up at createHangUpError (_http_client.js:331:15) at TLSSocket.socketCloseListener (_http_client.js:363:23) at emitOne (events.js:121:20) at TLSSocket.emit (events.js:211:7) at _handle.close (net.js:554:12) at TCP.done [as _onclose] (_tls_wrap.js:356:7) code: 'ECONNRESET' } 
2018-07-10 11:31:49 [err] [ManagerDrivers] [radar] [0] Error: Connection timeout at ClientRequest.req.setTimeout (/drivers/radar/device.js:238:12) at Object.onceWrapper (events.js:313:30) at emitNone (events.js:106:13) at ClientRequest.emit (events.js:208:7) at TLSSocket.emitTimeout (_http_client.js:708:34) at Object.onceWrapper (events.js:313:30) at emitNone (events.js:106:13) at TLSSocket.emit (events.js:208:7) at TLSSocket.Socket._onTimeout (net.js:407:8) at ontimeout (timers.js:475:11) 

What I have done:
Installed and removed it, installed it again, same thing happens
Restart of app dosen´t help

Have 2 radars installed with flows, one for airplanes within 10 km distance, and one for helicopters within a distance of 2 km 

Regards Erik

**Comment by gruijter** [comment]
new version just uploaded to GitHub, and will be released in Homey app store in a few days probably. Please let me know if this fixes your problem.

**Comment by dkduck** [comment]
Sounds great, and thanks for great and fast service.
I`m not sure how to install from github

**Comment by gruijter** [comment]
It just got released in the appstore :)

**Comment by dkduck** [comment]
Still not working :-(

Getting thes errors now:

2018-07-11 14:26:57 [err] [ManagerDrivers] [radar] [1] adsbexchange service error: 522 
2018-07-11 14:22:56 [err] [ManagerDrivers] [radar] [1] adsbexchange service error: 522 
2018-07-11 13:39:00 [err] [ManagerDrivers] [radar] [0] adsbexchange service error: 522 
2018-07-11 12:00:05 [log] [VirtualRadarApp] app unload called 
2018-07-11 10:03:34 [log] [VirtualRadarApp] app unload called 
2018-07-11 02:00:01 [log] [VirtualRadarApp] app unload called 
2018-07-10 21:47:56 [err] [ManagerDrivers] [radar] [1] adsbexchange service error: 520 
2018-07-10 20:41:59 [err] [ManagerDrivers] [radar] [0] adsbexchange service error: 520 
2018-07-10 20:41:59 [err] [ManagerDrivers] [radar] [1] adsbexchange service error: 520 
2018-07-10 18:09:52 [err] [ManagerDrivers] [radar] [0] adsbexchange service error: 522 
2018-07-10 18:02:09 [log] [VirtualRadarApp] app unload called 
2018-07-10 17:37:22 [err] [ManagerDrivers] [radar] [1] Error: error: 520 
2018-07-10 16:50:27 [err] [ManagerDrivers] [radar] [1] Error: error: 522 
2018-07-10 16:23:26 [err] [ManagerDrivers] [radar] [1] Error: error: 522 
2018-07-10 15:49:25 [err] [ManagerDrivers] [radar] [1] Error: error: 522 
2018-07-10 15:32:15 [err] [ManagerDrivers] [radar] [0] Error: error: 522 
2018-07-10 14:45:14 [err] [ManagerDrivers] [radar] [0] Error: error: 522 
2018-07-10 14:34:23 [err] [ManagerDrivers] [radar] [1] Error: error: 522 
2018-07-10 14:33:23 [err] [ManagerDrivers] [radar] [1] Error: error: 522 
2018-07-10 14:33:13 [err] [ManagerDrivers] [radar] [0] Error: error: 522 
2018-07-10 14:31:13 [err] [ManagerDrivers] [radar] [0] Error: error: 522 
2018-07-10 14:28:13 [err] [ManagerDrivers] [radar] [0] Error: error: 522 
2018-07-10 14:22:45 [radar] [1] { Error: socket hang up at createHangUpError (_http_client.js:331:15) at TLSSocket.socketCloseListener (_http_client.js:363:23) at emitOne (events.js:121:20) at TLSSocket.emit (events.js:211:7) at _handle.close (net.js:554:12) at TCP.done [as _onclose] (_tls_wrap.js:356:7) code: 'ECONNRESET' } 
2018-07-10 14:22:45 [err] [ManagerDrivers] [radar] [1] Error: Connection timeout at ClientRequest.req.setTimeout (/drivers/radar/device.js:238:12) at Object.onceWrapper (events.js:313:30) at emitNone (events.js:106:13) at ClientRequest.emit (events.js:208:7) at TLSSocket.emitTimeout (_http_client.js:708:34) at Object.onceWrapper (events.js:313:30) at emitNone (events.js:106:13) at TLSSocket.emit (events.js:208:7) at TLSSocket.Socket._onTimeout (net.js:407:8) at ontimeout (timers.js:475:11)

**Comment by gruijter** [comment]
mmh. Error 520 and 522 means that you get errors when trying to retrieve ADS-B info from adsbexchange.com. You say it does work for some hours, and then it stops?

Can you get live data from https://global.adsbexchange.com/VirtualRadar/desktop.html with a pc? Or are you in a country where they block usage of adsbexchange maybe?

Could you post the settings of your radar 0? (e.g. by posting some screenshots?)

**Comment by gruijter** [comment]
Ok, i set the same range, altitude, scan interval and also disabled helicopter. My radar is still going strong after 5 hrs. Maybe it has to do with your location? Did you try setting just 1 radar with 5km range on another lat/lon?

**Comment by dkduck** [comment]
Removed app, installed and made 1 radar, in another location, nearby an airport with 5 km range.
Nothing happend, tried this morning to increase the range 25 km, covering the airport...still nothing.

Tried several times checking connection to adbse homepage, both on iPad and PC, had no trouble getting in there and could see everything.

latest log:
2018-07-12 07:38:16 [err] [ManagerDrivers] [radar] [0] adsbexchange service timeout 
2018-07-12 06:40:36 [radar] [0] device init sensor Radar_1} 
2018-07-12 06:40:26 [radar] [0] scanner device settings changed 
2018-07-12 05:01:20 [err] [ManagerDrivers] [radar] [0] adsbexchange service error: 503 
2018-07-11 23:00:40 [radar] [0] device init sensor Radar_1} 
2018-07-11 23:00:30 [radar] [0] scanner device settings changed 
2018-07-11 22:48:04 [radar] [0] device init sensor Radar_1} 
2018-07-11 22:47:54 [radar] [0] scanner device settings changed 
2018-07-11 22:31:50 [radar] [0] device init sensor Radar_1} 
2018-07-11 22:31:40 [radar] [0] scanner device settings changed 
2018-07-11 22:21:18 [radar] [0] device init sensor Radar_1} 
2018-07-11 22:21:08 [radar] [0] scanner device settings changed 
2018-07-11 22:20:42 [radar] [0] scanner added: Radar_1 Radar_1 
2018-07-11 22:20:42 [radar] [0] device init sensor Radar_1} 
2018-07-11 22:20:36 [radar] [ { name: 'Radar_1', data: { id: 'Radar_1' }, settings: { pollingInterval: 20, lat: 56.082665150069836, lng: 10.022553563754286, altLm: 0, altUm: 12000, dstU: 5, mil: false, int: false, sqk: '0000', unknown: true, land: true, sea: true, amphibian: true, helicopter: true, gyrocopter: true, tiltwing: true, vehicle: true, tower: true, onlyGnd: false, onlyAir: true } } ] 
2018-07-11 22:20:09 [err] [VirtualRadarApp] error reading logfile: ENOENT: no such file or directory, open '/userdata/log.json' 
2018-07-11 22:20:09 [tracker] ScannerDriver onInit 
2018-07-11 22:20:09 [radar] ScannerDriver onInit 
2018-07-11 22:20:09 [log] [VirtualRadarApp] capturing stderr

**Comment by gruijter** [comment]
Weird... I see you did get a valid reading after app init, and that you changed the radar settings a few times after that. What did you change?

And what happens if after a fresh app install you add one radar and leave it at the default settings?

**Comment by gruijter** [comment]
I made a radar on your home location, and only changed the range to 50km. It works without problem on my homey...

2018-07-12 09:41:24 [radar] [1] { dst: 22.72, brng: 153.9, alt: 11302, spd: 818, vsi: 0, gnd: false, mil: false, help: false, species: 'land', icao: 4CA8E4, reg: EI-ENR, call: RYR2577, mdl: 'Boeing 737NG 8AS/W', op: 'Ryanair', from: 'LEMG Málaga, Spain', to: 'ESOW Stockholm Västerås, Stockholm / Västerås, Sweden' }

**Comment by dkduck** [comment]
First change is location, the next 3 is distance

This is very strange you get data without problems, Ill try remove the radar and add a new one at my own location with 500 km

**Comment by dkduck** [comment]
Deleted radar_1

Made a new radar with name Radar_Test_01, only changed the range to 50km

2018-07-12 10:37:44 [radar] [0] device init sensor Radar_Test_01} 
2018-07-12 10:37:34 [radar] [0] scanner device settings changed 
2018-07-12 10:37:21 [radar] [0] scanner added: Radar_1 Radar_Test_01 
2018-07-12 10:37:21 [radar] [0] device init sensor Radar_Test_01} 
2018-07-12 10:37:07 [radar] [ { name: 'Radar_1', data: { id: 'Radar_1' }, settings: { pollingInterval: 20, lat: 56.082665150069836, lng: 10.022553563754286, altLm: 0, altUm: 12000, dstU: 5, mil: false, int: false, sqk: '0000', unknown: true, land: true, sea: true, amphibian: true, helicopter: true, gyrocopter: true, tiltwing: true, vehicle: true, tower: true, onlyGnd: false, onlyAir: true } } ] 
2018-07-12 10:36:06 [radar] [0] scanner deleted: Radar_1 Radar_1

**Comment by dkduck** [comment]
Instantly I got data, now I think it is strange, let us see later today how it behave.
Only change is radar name ????

2018-07-12 10:39:05 [radar] [0] icao: 484F15, leaving airspace! 
2018-07-12 10:38:05 [radar] [0] { dst: 37.13, brng: 21.7, alt: 9367, spd: 861, vsi: -1248, gnd: false, mil: false, help: false, species: 'land', icao: 484F15, reg: PH-BGU, call: KLM91E, mdl: 'Boeing 737NG 7K2/W', op: 'KLM Royal Dutch Airlines', from: undefined, to: undefined } 
2018-07-12 10:38:05 [radar] [0] { dst: 43.15, brng: 236.7, alt: 2961, spd: 603, vsi: 1112, gnd: false, mil: false, help: false, species: 'land', icao: 4CA65F, reg: EI-FPE, call: SAS2498, mdl: 'Bombardier CRJ 900 LR NG', op: 'Scandinavian Airlines System', from: 'EKBI Billund, Denmark', to: 'ESSA Stockholm-Arlanda, Stockholm, Sweden' }

**Comment by gruijter** [comment]
there is an issue when deleting a radar, and then trying to add a new one again. I will have that fixed in a new version. Maybe that is what messed up your configuration.

Anyhow. let me know if the problem resurfaces. I will close this issue for now.

Good luck!
